### ISSUE TITLE
ATV+ working at X1C6?

### ISSUE THREAD

**Issue by Hochiss** [tylernguyen/x1c6-hackintosh#133]
mine can play ATV trailer but movie not. 

Checking TMX86 at [[1](https://www.tonymacx86.com/threads/apple-tv-problem.297179/)] & [[2](https://www.tonymacx86.com/threads/an-idiots-guide-to-lilu-and-its-plug-ins.260063/)], seems only work certain desktop SMBIOS type and requires dedicated GPU onboard,  and shiki mask values(boot).

As indicated at [acidanthera/WhateverGreen](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md), if I understood correctly, for integrated GPU like HD620 for X1C6, no chance to work? But then, some real Macs (e.g. MacAir) also don't have dedicated GPU still works, why? 

on the other side, Does it work at BigSur?

**Comment by rajandtonic** [comment]
As far as I'm aware, genuine Apple devices pass off hardware DRM to the T2 chip or the iGPU's built-in decoders if on a model without the chip. In the case of the iGPU, the Management Engine doesn't have Apple's certificates in, and as such it won't work.

Rather than using the standard setup of Intel being the authority for EPID attestation, Apple themselves control this aspect. As such, rather than using Intel's collection of public keys from the EPID signing, Apple has their own. In a nutshell, this means Apple doesn't have the Intel keys, and most likely only encrypt their content expecting keys that trace back to an Apple-owned EPID public key. After all, from their perspective, why bother signing extra keys with your authority certificate if you're only using specific chips in a specific way in a specific environment. To attempt to provision an Apple key onto your machine would be difficult too since you'd need the group public key that matches up with your machines private key that is then **ALSO** associated with Apple's EPID authority cert.

Previous versions of macOS (pre-Big Sur) allowed software decoders in Safari for the majority of DRM enabled content, but this has been phased out now in favour of the more efficient and in some ways more secure, hardware methods. WEG works in the case of a Mac without an iGPU, by enabling the AMD hardware decoders built into the GPUs - interesting when you consider that Apple removed a lot of older hardware decoders (though it's fair to assume they only made up a tiny percentage anyway).

Realistically, the best option at the moment is to use a browser that supports software decoding (i.e. Chrome with Widevine) rather than hardware to access DRM protected content.

Hope this helps

**Comment by rajandtonic** [comment]
As far as I'm aware, genuine Apple devices pass off hardware DRM to the T2 chip or the iGPU's built-in decoders if on a model without the chip. In the case of the iGPU, the Management Engine doesn't have Apple's firmware in, and as such it won't work.

Apple themselves control part of the ME's firmware. As such, rather than using the standard Intel ME firmware, there are some extra binary blobs etc baked in by Apple. Unfortunately I'm not privy to what they are or what they do, but it'd be reasonable to assume it has something to do with establishing the protected audio/video path, since macs set some specific bits on PAVP compared to Windows machines, though the exact ones escape me.

I also *think* that Apple currently maintains their own EPID public keys, rather than using Intel's: rather than using Intel's collection of keys from the EPID signing, Apple has its own. In a nutshell, this means Apple most likely only encrypts their content expecting keys that trace back to an Apple-owned EPID public key. To attempt to provision an Apple key onto your machine would be difficult, but possible if you can get the group public key that matches up with your machines private key. You'd then just hit the roadblock of PAVP - not sure how you'd get past that, to be honest - I'm a lot better versed in Widevine as opposed to Fairplay.

Previous versions of macOS (pre-Big Sur) allowed software decoders in Safari for the majority of DRM enabled content, but this has been phased out now in favour of the more efficient and in some ways more secure, hardware methods. WEG works in the case of a Mac without an iGPU, by enabling the AMD hardware decoders built into the GPUs - interesting when you consider that Apple removed a lot of older hardware decoders (though it's fair to assume they only made up a tiny percentage anyway).

Realistically, the best option at the moment is to use a browser that supports software decoding (i.e. Chrome with Widevine) rather than hardware to access DRM protected content.

Hope this helps
