### ISSUE TITLE
[USB] USB Accessories Disabled

### ISSUE THREAD

**Issue by RyoIkarashi** [tylernguyen/x1c6-hackintosh#34]
## Issue

When I plug my iPhone into x1c6 via USB, the alert saying **`USB Accessories Disabled - Unplug the accessory using too much power to re-enable USB devices.`** always shows up.

## Screenshot

![Screen Shot 2020-02-08 at 20 43 46](https://user-images.githubusercontent.com/5750408/74084620-25627680-4ab4-11ea-91fb-9d85ee933b21.png)

How can I fix this issue? (Here is my [EFI](https://github.com/RyoIkarashi/hackintosh-x1c6-with-native-wifi-card))

**Comment by tylernguyen** [comment]
@RyoIkarashi What iPhone model do you have? I cannot replicate this issue.

**Comment by RyoIkarashi** [comment]
@tylernguyen Thanks for the reply!
Here is a piece of info of my iPhone.

| | |
| ---- | ---- |
| Software Version | 13.3.1 |
| Model Name | iPhone 6s |
| Model Number | NKQP2J/A |

**Comment by RyoIkarashi** [comment]
After upgrading iOS from `13.3` to `13.3.1`, I think the issue went away.

**Comment by Ranguvar** [comment]
@tylernguyen Would you mind re-opening this?

Having this issue now on my X1C6 20KH with my 2018 iPad Pro.

Android phone works fine, but the iPad connected to either USB-A or either USB-C only establishes a data link for a moment before kicking off due to too much power draw.

I did catch a screenshot of System Information while it was on.

![Image 5-20-20 at 12 36 AM](https://user-images.githubusercontent.com/309531/82405810-f0f74280-9a32-11ea-825d-2195b8a5619f.jpeg)

I also found an old post of someone discussing the injection of those USB power limits, so I may try that: https://www.reddit.com/r/hackintosh/comments/3oflxd/no_power_from_usb_30ports/cvx139e/

**Comment by Ranguvar** [comment]
Resolved by adjusting kUSBSleepPortCurrentLimit and kUSBWakePortCurrentLimit from 3000 to 1000 in the USBPorts.kext Info.plist.

I'll try playing with those values more.

**Comment by tylernguyen** [comment]
@Ranguvar 
I can't replicate this with my iPad mini, what iPad model do you have and what iOS is it on?

**Comment by guinanseyebrows** [comment]
> Resolved by adjusting kUSBSleepPortCurrentLimit and kUSBWakePortCurrentLimit from 3000 to 1000 in the USBPorts.kext Info.plist.
> 
> I'll try playing with those values more.

This worked for me as well for both my iPhone running iOS 12 as well as an external hard drive that was taking a long time to mount before (over 30 seconds between plugging in and becoming available in Finder).
