### ISSUE TITLE
Question about acpi patching

### ISSUE THREAD

**Issue by Jamesxxx1997** [tylernguyen/x1c6-hackintosh#46]
Hi~
I'm a user of thinkpad x1 yoga 2018, with its specs similar to x1 carbon 2018
I have some question about acpi patching~

1. there is a bunch of acpi error when using the hotpatch , will this effect the system stability and cause issue?

![IMG_8765](https://user-images.githubusercontent.com/29252582/78902306-33307a00-7aac-11ea-8e66-11d1aa84a015.jpg)

2. Do you have guide about traditional DSDT patch about x1 carbon 2018 ?

Thanks!

**Comment by tylernguyen** [comment]
@Jamesxxx1997 Systems specs do not determine the likeness of ACPI tables. Two machines can have similar devices but be configured as different names or paths under the ACPI table. Hence, my hotpatches will not translate well to your X1 Yoga 2018. This is especially apparent within the keyboard SSDT patch, where some of my Fn keys will most lilkely not match with yours.

Extract your source DSDT, use a diff program to compare it with my own source DSDT. And you will see how different the two tablesets are.

In addition, OpenCore does not play well with static DSDT patching. So I would recommend trying to learn SSDT hot patching instead, as it is a better solution anyway.

Since I do not have an X1 Yoga to test myself and help you. I can only point you towards what I would try:

Firstly, please **carefully** go through my [ACPIPatching.md](https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/4_README-ACPIpatching.md). It has the reasons as to why each patch is used, their corresponding OpenCore patches, and **the device** that the SSDT patches

Secondly, please take a look at [OC-little](https://github.com/daliansky/OC-little). That repo is a great collection of reference hotplug SSDT patches that can be modified for your machine. Simply use Google Translate to read the repo's docs.

Finally, the [Vanilla Laptop Guide](https://fewtarius.gitbook.io/laptopguide/) and [Getting Started with ACPI](https://khronokernel.github.io/Getting-Started-With-ACPI/) are great resources for starters to read.

Again, I do not have an X1 Yoga. So I cannot help you with the actual testing and debugging. But if you have any other general questions. Post it here and I will try my best.

**Comment by tylernguyen** [comment]
I forgot to mention this. But as I optimize this repository for the X1C6, it will increasingly become more incompatible with other machines. I understand that all this ACPI talk can be daunting. But if you spend some time looking into different guides and resources, it will greatly benefit your build.

**Comment by Jamesxxx1997** [comment]
Sorry ,  I've reupload the acpi error [image](https://drive.google.com/file/d/14lbekbV0sWjYtn-ib5Vhg1IxrCT5aD_G/view?usp=sharing) 



**About traditional static patch**

> Extract your source DSDT, use a diff program to compare it with my own source DSDT. And you will see how different the two tablesets are.

Thanks you again for your detailed explanation , I will do that ASAP. But now I have to prepare for a big exam and I am still using the clover and traditional static patch ; if you have time , can you help taking a look at my patch ? Just want to check whether I do anything wrong or not, Thanks. (Afraid break my machine again when turn to hotpatch , since x1 yoga is my daily driver)

I've dump my dsdt and patching it according to [our guide](https://www.tonymacx86.com/threads/guide-thinkpad-x1-yoga-3rd-gen-20ld-with-mojave.261823/post-1822531).
using these dsdt fix
i.	[sys] Fix _WAK Arg0 v2
ii.	 [sys] Fix Mutex with non-zero SyncLevel
iii.	 [bat] Lenovo x230i 
iv.	[sys] OS Check Fix (Windows 10)
v.	[sys] RTC Fix
vi.	[sys] IRQ Fix
vii.	[sys] SMBUS Fix
viii.	 [sys] HPET Fix
ix.	 [sys] Shutdown restart (XHC.PMEE) Fix
x.	Brightness dsdt Fix (F5,F6 for control brightness)
xi.	[usb] USB3 _PRW 0x6D Skylake (Instant wake) 

and adding some hotpatch , including
1.  SSDT-PNLF
2. SSDT-PTSWAK (from [P little](https://github.com/daliansky/P-little))
3. SSDT-USBX
4. SSDT-UIAC
5. SSDT-Thinkpad_Clickpad

[My efi folder](https://drive.google.com/file/d/1l9BMPzd9cYg_emVc6Vjf_BF4X-iwDvbT/view?usp=sharing)
