### ISSUE TITLE
Would this work for the 5th generation as well?

### ISSUE THREAD

**Issue by xximranxx** [tylernguyen/x1c6-hackintosh#5]

**Comment by tylernguyen** [comment]
Hello @xximranxx 

The guide, generally, should work for the 5th generation as well. Although certain files and patches are going to differ due to separate hardware. I recommend you look at this guide for the 5th gen carbon https://www.tonymacx86.com/threads/99-perfect-sierra-10-12-6-on-thinkpad-x1-carbon-5th-gen-with-dual-boot-unchanged-win7.237922/
