### ISSUE TITLE
Questions about PollAppleHotKeys

### ISSUE THREAD

**Issue by H15teve** [tylernguyen/x1c6-hackintosh#52]
I tried to disable ShowPicker and press cmd/option/esc(alt/win/esc) to boot into the picker GUI but didn't work. Tested with and without openusbkbdxe.efi/ps2mousedxe/ps2keyboarddxe. Other Misc config strictkly followed this project. I wonder whether it's an individual case, thx TAT

**Comment by tylernguyen** [comment]
@H15teve To show picker during boot sequence, using the Esc key. See OpenCore https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf

Note that you you have to time this after the Lenovo boot logo, otherwise you it will enter diagnostics. Though you can just exit diagnostics and press Esc key again to show picker.
