### ISSUE TITLE
Battery and Thunderbolt 3

### ISSUE THREAD

**Issue by chadharnav** [tylernguyen/x1c6-hackintosh#54]
I want to use an rx580 egpu for editing and external displays but thunderbolt 3 is not working at all. I also cannot see battery level at all. Any tips. Fyi ur guide worked perfectly

**Comment by velaar** [comment]
There is a way to use this GPU. But it has its trade-offs.  See the thunderbolt issue.

**Comment by zacharysalvatore** [comment]
I’m buying Razer core X and 5700xt and it will ship to my home very soon. I’ll test eGPU not rh following day. I’ll report after.

**Comment by Porco-Rosso** [comment]
I currently have a Razer Core X and 5700xt as well. 
With some back and forth with Tylernguyen we got it working, but:
1. Hotplug is not working
2. I couldn't get the graphics card display ports to drive my monitor
So some more work is still needed with the TB3 interface.

**Comment by velaar** [comment]
I have an Rx590 and I do have the internal monitor acceleration and hot UNplug. But no hot plug. Also have the benefit of lower power usage under BIOS assist = ON 

The settings are:
* Thunderbolt reset (efi) disabled
* Thunderbolt SSDT (v1)
* Thunderbolt bios assist ON
* Thunderbolt pre-boot - enabled
* Reset kext - disabled

But I have issues with USB-C.  It is unstable.

**Comment by tylernguyen** [comment]
@chadharnav Like others have said, there are a few quirks with the TB3 hotplug fix right now. Please keep TB3 related discussion in that issue for easy referencing. 

I have been investigating flashing the native macOS Thunderbolt firmware but I will not publish that until I have confirm the process is stable as I don't want anyone to brick their expensive machines. I really have no timeline on this.

Regarding battery level, it is fixed by [patches/SSDT-OCBAT0-TP_tx80_x1c6th.dsl](https://github.com/tylernguyen/x1c6-hackintosh/blob/master/patches/SSDT-OCBAT0-TP_tx80_x1c6th.dsl) and [patches/OpenCore%20Patches/TPbattery.plist](https://github.com/tylernguyen/x1c6-hackintosh/blob/master/patches/OpenCore%20Patches/TPbattery.plist)

Make sure you show battery icon within macOS preferences.

**Comment by chadharnav** [comment]
Found solution for thunderbolt. Start with it inserted
