### ISSUE TITLE
Battery Status Not working

### ISSUE THREAD

**Issue by chadharnav** [tylernguyen/x1c6-hackintosh#55]
I cannot enable battery Status
What should I do?

**Comment by velaar** [comment]
@chadharnav  What troubleshooting steps did you take? Are you sure that all the SSDTs are loaded? Please share at least your config.plist or better eat whole EFI folder.

**Comment by tylernguyen** [comment]
@chadharnav Per my last response, battery level is fixed by patches/SSDT-OCBAT0-TP_tx80_x1c6th.dsl and patches/OpenCore%20Patches/TPbattery.plist

Make sure you show battery icon within macOS preferences.

If you still cannot get it to work, please provide appropriate EFI dump and diagnostics so others can help you.

Moving forward, I will also create an issue template on this repo.
