### ISSUE TITLE
Moving the repo to MacOS X 11 Big Sur

### ISSUE THREAD

**Issue by velaar** [tylernguyen/x1c6-hackintosh#58]
This is a placeholder for a discussion / feature request. Wanted to start gathering data and maybe run some tests in the coming weeks.

**Comment by H15teve** [comment]
Tiny enhancement: Big Sur brings the chime back. Suggest an optional patch to config.plist to enable UEFI-audio configuration being added.

**Comment by tylernguyen** [comment]
> 
> 
> Tiny enhancement: Big Sur brings the chime back. Suggest an optional patch to config.plist to enable UEFI-audio configuration being added.

@H15teve Noted. I will add support for boot chime with `AudioDxe`

**Comment by tylernguyen** [comment]
@H15teve 

Ok, it turns out that boot chime support is going to be complicated than I had thought. Currently, `ALC285` only supports 48kHz on its stereo out (https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/references/ALC285_codec.txt). However, [acidanthera/OcBinaryData](https://github.com/acidanthera/OcBinaryData) audio files are all sampled to 44.1kHz. So `AudoDxe` will simply not play them.

OC devs are aware of this: https://github.com/acidanthera/bugtracker/issues/740

For now, one way to get around this is to using something Audacity to resample audio files to 48kHz. However, this is is very inefficient, especially if you plan on resampling other audio files for accessibility as well as the boot audio file.

Though that is not the sole problem. With the audio resampled to 48kHz, the boot chime will play but then cut off, a sort of lag. So it doesn't match up with the Apple logo. Again, OC devs are also aware of this issue: https://github.com/acidanthera/bugtracker/issues/971

The complicated thing is that the fix for the second issue requires setting a delay code in OC, then manually compiling the bootloader files (since the delay itself varies vendor to vendor and probably machines to machines)

**Comment by tylernguyen** [comment]
Preliminary play chime support added in a598de6
Disabled by default, enable it if you want. Currently using the audio file up-sampled by me using Audacity until `AudioDxe` can do so on the fly.

**Comment by ajhutton** [comment]
I've gotten chime support working thanks to your instructions and resampled WAV file.

Regarding the second issue of setting a delay in OC - is it possible to pad the WAV file with some silence to achieve this or is it not played async to the boot process?

Regarding Big Sur itself I have managed to successfully get all the way to the last 'installing' screen after a reboot. I am getting stuck on 'about a minute remaining' at the apple logo. (left it alone like this for 5 hours and then 9 hours on different attempts with no success)

Pressing ⇧⌃⌥⌘W (which in the past few versions of OS X) has dropped back to the traditional installer interface from which the log can be viewed but for some reason this isn't doing anything for me. I don't know if it's rollover with the keyboard or maybe they've changed things in Big Sur but ultimately this is leaving me with only a vague description of "it gets to here and then doesn't go any further".

Does anybody know where I would find the logs from this portion of the install?

**Comment by velaar** [comment]
@tylernguyen Did you do any BigSur testing? As the update is coming out soon I can update.We might need to look into #24 again as I have freezes and still struggle to have a working eGPU setup.

**Comment by notthebee** [comment]
@velaar I did test the latest beta – just dirty installed it on top of my current Catalina installation. One issue that I ran into is not being able to enter "Security & Privacy" menu in Settings 
![Error](https://user-images.githubusercontent.com/30384331/93258361-b194f480-f78d-11ea-9407-00237ea54f36.png)
I've tried all the solutions I could find on the Internet, and juding by the r/Hackintosh Discord I'm not the only one who's experienced tihs. Nobody knows why this happens but in some cases changing the SMBIOS helps (it didn't for me).

**Comment by velaar** [comment]
@notthebee  

I wonder it it went away with the latest repo 0.6.2 OpenCore has lots of fixes for this problem specifically

**Comment by velaar** [comment]
@tylernguyen updated to BigSur. Other than some power consumption issues all looks good. 

Power consumption is TBD as I'm running a heavily-debug version. 


Also, **please note** that BIOS v.1.50 is compatible with the mods and works as expected. (Personally noticed a bit faster boot time)

**Comment by tylernguyen** [comment]
Just as @veelar stated, the repo is perfectly setup for Big Sur without any issues.

I myself have upgraded via a clean install and recommend others to do so as well. I will now close this transition issue. Specific issues should be created on a case-by-case basis.
