### ISSUE TITLE
10.15.5 issues with OC059?

### ISSUE THREAD

**Issue by outdoormagic** [tylernguyen/x1c6-hackintosh#63]
Hi everyone,

Not the best place to ask, though I didn't know where would be better.

I have the exact same configuration as Tyler. Updated OC 0.5.9 on 10.15.4, no issues. Tried to run update to 10.15.5 and laptop panics when in MacOS installer, creating boot loop. Can still boot into 10.15.4 just fine via picker.

10.15.5 updated fine with OC 0.5.9 on Z390 Designare.

Anyone seeing this issue on Thinkpad? If not, then I messed up something and will reinstall. Otherwise, glad to provide logs, dumps, and such.

--P.

**Comment by tylernguyen** [comment]
@outdoormagic 

Are you using my EFI-OpenCore folder are have you customized something? I upgraded to 10.15.5 without any issues. And it would be great if you could provide panic logs so we can tell why the machine is boot looping. In addition, per [docs/5_README-other.md](https://github.com/tylernguyen/x1c6-hackintosh/blob/master/docs/5_README-other.md), please clear NVRAM as a precaution.

**Comment by tylernguyen** [comment]
@outdoormagic 
It is likely due to the Kaby Lake Graphics patches. See https://github.com/tylernguyen/x1c6-hackintosh/issues/40#issuecomment-659370165

I will make a note of this in the repo on the next commit. Though moving forward, I may default to the stock config and leave the graphics patches disable by default for only those who need it.
