### ISSUE TITLE
USB improvements

### ISSUE THREAD

**Issue by Chivs** [tylernguyen/x1c6-hackintosh#70]
In the course of enabling BT wake, I've made a few changes to the OC configuration which is working reliably for me, without any side effects. Wake on BT now work reliably. With a couple of advanced BIOS tweaks, I can now draw < 1.0 on battery.

The core changes are detailed below, and you can refer to the OC folder attached.
- Changed USB configuration from the kext implementation to an SSDT implementation. Requires the SSDT-Xhci file and the UPC patch.
- Removed all PTS/WAK patches and their corresponding SSDT's
- Made changes to the USB configuration for SSDT-Z390-TB3HP to add additional port attributes for companion ports and fixed the mapping. This also seems to lower power draw.

[Modified OC.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/5003846/Modified.OC.zip)

**Comment by tylernguyen** [comment]
@Chivs 

`SSDT-XHCI` seems rather bloated. There are many devices in there that do not exist on our machine. In addition, I do not see why this is better than mapping USB and injecting them via a kext. 

Also, a note: it helps that when sharing to acpi patches to also share source `.dsl` with comments. In this case, it would be nice for comments to label which device is which corresponding ports on the machine.

Also, how are you testing BT wake? I want to replicate testing with my current setup and your proposed changes.

**Comment by Chivs** [comment]
@tylernguyen 

Yes, the additional ports don't need specifying, I left them in during testing. I have attached an updated version with only the needed ports defined.
As for whether this method is better than the kext version, I guess it's a matter of preference. My reasoning was:
- All the USB patches can be put into a single SSDT
- This method is closer to a real Mac, as you don't end up with attributes on the XHC device to specify port count etc. Correctly specifying the port capabilities in AHCI seemed better to me.

I didn't see the need for all the GPRW overrides, PTS and WAK patches, as they prevented 'natural' wakeups on the laptop, especially around BT. If there's a very specific reason why you feel you need (some of) them, please let me know.

I test BT wake with a Magic Mouse and keyboard connected to my X1 and use it lid closed to two external 4k monitors. It sleeps automatically just fine and clicking the mouse will wake it up.


[SSDT-Xhci.aml.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/5006724/SSDT-Xhci.aml.zip)

**Comment by Porco-Rosso** [comment]
If there are no downsides, I would support this change, as it would also help with my BT wake situation. Many of us seem to be using a dock and monitors. It would also be closer to native Mac functionality.

**Comment by Chivs** [comment]
> If there are no downsides, I would support this change, as it would also help with my BT wake situation. Many of us seem to be using a dock and monitors. It would also be closer to native Mac functionality.

@Porco-Rosso feel free to give this a try and let me know if your BT wake works correctly.

**Comment by tylernguyen** [comment]
@Chivs 

Did you ever resolve the display issue? I want to isolate these problems.

**Comment by tylernguyen** [comment]
@Porco-Rosso 

If possible, test BT wake functionality of the current setup and @Chivs's proposed changes and let me know the difference.

**Comment by tylernguyen** [comment]
@Chivs 
Using my current EFI folder, BT wake works with my Logitech MX Master 2S. Though I did my testing without external displays and with the lid open.
Did you only have issues with BT wake with the lid closed? or did you also have it with the lid open?

**Comment by Chivs** [comment]
@tylernguyen I believe it was under any circumstance because the sleep/wake patches in your EFI effectively disable this capability completely. 

I'll have to try the display issue a few more times, I've been focused on the BT issues and also experimented with the TB patches.

**Comment by tylernguyen** [comment]
> 
> 
> @tylernguyen I believe it was under any circumstance because the sleep/wake patches in your EFI effectively disable this capability completely.
> 
> I'll have to try the display issue a few more times, I've been focused on the BT issues and also experimented with the TB patches.

That's not right then. BT wake is working fine for me right now. What network card are you using?

**Comment by Chivs** [comment]
The Apple CS2 card with adapter.

**Comment by tylernguyen** [comment]
> 
> 
> The Apple CS2 card with adapter.

That's my current card as well. And BT wake is working normally for me.
In any case, I do not see why this would be a USB patching issue, the two methods are specifying the same definitions.

Please run `pmset -g` to check your current sleep settings.

I would ask to try again cleanly with my current EFI folder. Again, BT wake is working normally for me with this setup.

**Comment by Chivs** [comment]
> **EDIT:** Also, a note, if you want to go down patching USB using this method, the **x1c6 does not need `_UPC` to `XUPC`** renames. You can remove that patch.

Don't think so, the _UPC method is defined in SSDT-4, so in order to override it, it needs to be renamed. The patch I included only overrides _UPC in this SSDT. Unless I'm missing something.

**Comment by tylernguyen** [comment]
> Don't think so, the _UPC method is defined in SSDT-4, so in order to override it, it needs to be renamed. The patch I included only overrides _UPC in this SSDT. Unless I'm missing something.
You're right. I missed the OEMTableID. I'll cross out my previous comment.

**Comment by Chivs** [comment]
> Also, I would advise against removing `SSDT-PTSWAK` and its related extension patches. Without them, you may encounter a bug where shutdown become reboots; they also patch lid wake functionalities.
> 
There are other patches which are still enabled to resolve the shutdown issue. I get a crash on sleep if I re-enable the PTSWAK SSDT and patches.

> In addition, `GPRW` is to fix "instant wake" problems whereby macOS would be woken by USB upon entering sleep.
> 
This one is interesting, because the patch would absolutely stop wake on BT, as it is a USB wake event. 
> Edit: If you want to see why certain ACPI patches are included in my setup, they're all documented under my docs/4_README_ACPI-Patching
> 
> If you have removed those patches, please check your sleep logs, I suspect that your machine is actually not sleeping. Hence why you feel that your BT wake is now working. Again, I do think that BT wake is a separated issue (most likely a setup issue), not related to USB nor current patches, as it is working currently for me.

Sleep is working fine, fan shuts off, button flashes. Only active processes prevent sleep, such as backupd, or the Intel Power Gadget if you leave it running.

**Comment by tylernguyen** [comment]
> There are other patches which are still enabled to resolve the shutdown issue. I get a crash on sleep if I re-enable the PTSWAK SSDT and patches.

What do you mean "crashes on sleep"? This should not happen. There's nothing in PTSWAK that should cause a crash. As far as I can tell, sleep is has always been very stable for this project. Additionally, PTSWAK is necessary in battery patching.

> > In addition, GPRW is to fix "instant wake" problems whereby macOS would be woken by USB upon entering sleep.

> This one is interesting, because the patch would absolutely stop wake on BT, as it is a USB wake event.

Hooking `GPRW`, again, is to fix instant wake when entering sleep. It should have nothing to do with actual wake events during sleep.

**Again, all these patches are enabled for me and my BT wake is working fine me**, tested using MX Master 2S. So I am sure that is it not an issue with these patches. They are functional patches in my setup fixing the the aforementioned issues so I will not be removing them from my setup unless a better alternative is provided.

It would be better for you to look into sleep options with `pmset -g` which may reveal the true cause of your BT wake issues.

Additionally, since we only have our own cases to compare, it would be helpful if someone else can confirm whether BT wake is working on their machine, and with what setup. @veelar @Porco-Rosso @benbender or anyone else who can test with your own BT device.

**Comment by tylernguyen** [comment]
@Chivs 

I just tested my setup again without GPRW and the problems I used to have where by my always plugged in YubiKey would wake my machine seems to be gone. That was the original purpose as to why I had the patch in the setup.

So perhaps after few more testers can confirm the issue. we can come to a compromise and remove GPRW on the next commit. As it seems it is no longer need for me anyway and could possibly fix other issues.

**Comment by velaar** [comment]
I had GPRW patches on to avoid wake ups on GLAN was that resolved too?

**Comment by tylernguyen** [comment]
@velaar 

I didn't notice a problem with GLAN during my short period of testing. Though I have all Wake-on-Lan related options turned off in BIOS. In any sense, extended testing is probably needed.

**Comment by tylernguyen** [comment]
@velaar 

I've been sleeping the machine the entire day without problems with GPRW. Could you try disabling WOL in BIOS and try it without GPRW?

**Comment by tylernguyen** [comment]
@Chivs 

Can you please post your sleep logs? Maybe 30-1hr duration of sleep if you can.

**Comment by Sniki** [comment]
Mapping USB Ports with kext is better instead of ACPI.

Apple moved to kext USB implementation method since 10.11, even Acidanthera documented this, they documented that and added the link to the Apple Documentation regarding to this injection method.

Codeless USBPorts.kext is just perfect if you configure it correctly.

Reasons:
- Just a single kext for everything USB Related (even power properties can be injected there).
- No extra ACPI patches, no extra SSDTs
- You don't affect other operating systems in case of a dual or triple boot scenario with the same bootloader.
- You do it how Apple does on their Mac(s).
- No failures or problems in case of a change from a bios update.

**Comment by benbender** [comment]
@Sniki That's only true for USB-A 2.0/3.0-Ports. For USB-C 2.0/3.0/3.1/TB-Ports it's much more complicated, because there are multiple controllers involved which are mapped to the port depending on the device connected. Those Ports, on genuine Macs, have a companion-port-setup on those multiple controllers which can not be done via Kext afaik.

**Comment by benbender** [comment]
> EDIT 2: Tested again with my TEX Shinobi keyboard. I am sure that BT wake is functional for me.

@tylernguyen what bt-module/wifi card are you using atm?

**Comment by benbender** [comment]
@Chivs In opposite to my previous understanding, the T480 and X1C6 don't have a companion-port setup.USB2/3 is handled natively by the thunderbolt-controller (as seen by the HS-Ports on the controller). If it would be a companion-setup, there would be no hs-ports on the alpine ridge. This is indeed a good thing, because it drastically reduces the complexity for power-management in context of TB :)

**Comment by tylernguyen** [comment]
@Chivs GPRW is now removed from the repo's setup as of 985d3a2. Bluetooth wake should now function as expected.
